name: Build ZMK firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config
        uses: actions/checkout@v4

      - name: Build Corne (Left)
        uses: zmkfirmware/zmk-build-action@v1
        with:
          board: nice_nano_v2
          shield: corne_left

      - name: Build Corne (Right)
        uses: zmkfirmware/zmk-build-action@v1
        with:
          board: nice_nano_v2
          shield: corne_right
